name: CMake Build Matrix

on: [ push, pull_request ]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: "ubuntu-gcc-12"
            os: ubuntu-latest
            build_type: Release
            packages: ninja-build
            generator: Ninja
            cc: gcc-12
            cxx: g++-12
            bitness: ""
            artifact: ${{github.workspace}}/build/Benchmark/benchmark

          - name: "ubuntu-clang-15"
            os: ubuntu-latest
            build_type: Release
            packages: ninja-build clang-15
            generator: Ninja
            cc: clang-15
            cxx: clang++-15
            bitness: ""
            artifact: ${{github.workspace}}/build/Benchmark/benchmark

          - name: "windows-msvc-2022"
            os: windows-latest
            build_type: Release
            generator: "Visual Studio 17 2022"
            bitness: "-A x64"
            cc: cl
            cxx: cl
            artifact: ${{github.workspace}}/build/Benchmark/Release/benchmark.exe
            
          - name: "windows-msvc-2022-x86-debug"
            os: windows-latest
            build_type: Debug
            generator: "Visual Studio 17 2022"
            bitness: "-A Win32"
            cc: cl
            cxx: cl
            artifact: ${{github.workspace}}/build/Benchmark/Debug/benchmark.exe

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies on Ubuntu
      if: startsWith(matrix.config.os, 'ubuntu')
      run: |      
        sudo apt update
        sudo apt install ${{ matrix.config.packages }} -y

    - name: Configure CMake
      env:
        CC: ${{ matrix.config.cc }}
        CXX: ${{ matrix.config.cxx }}
      run: |
          cmake --version
          cmake ${{ matrix.config.bitness }} -G "${{ matrix.config.generator }}" -S . -B ${{github.workspace}}/build

    - name: Build    
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.config.build_type}}

    - name: Test
      working-directory: ${{github.workspace}}/build  
      run: ctest --verbose --no-tests=error -C ${{matrix.config.build_type}}

    - name: 'Upload artifacts'
      uses: actions/upload-artifact@v3
      with:
          name: benchmark-${{ matrix.config.name }}
          path: ${{matrix.config.artifact}}
          retention-days: 2
